### ISSUE TITLE
wxSVG does not work

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg-test-suite#15]
When I try to render with wxSVG it fails because it does not find libwxsvg.so.3

![Screenshot from 2020-03-02 19-16-36](https://user-images.githubusercontent.com/15687581/75704884-7da72580-5cba-11ea-945f-845d4cbe69ec.png)

This are my settings
![Screenshot from 2020-03-02 19-16-31](https://user-images.githubusercontent.com/15687581/75704899-84359d00-5cba-11ea-884f-50ec0ea5d7a0.png)

I downloaded https://sourceforge.net/projects/wxsvg/files/ and builded it in /home/jkalliau/prgm/wxsvg-1.5.22
```bash
.\INSTALL
.\configure
.\INSTALL
make
make install
sudo make install
```
I found it in `/home/jkalliau/prgm/wxsvg-1.5.22/src/.libs/libwxsvg.so.3`.

I think I could copy it to `/usr/lib`. But I think that might mess up my system?
Can I tell vdiff to use `/home/jkalliau/prgm/wxsvg-1.5.22/src/.libs/libwxsvg.so.3` for wxsvg?

**Comment by RazrFalcon** [comment]
>Can I tell vdiff to use /home/jkalliau/prgm/wxsvg-1.5.22/src/.libs/libwxsvg.so.3 for wxsvg?

Yes, by using:

```
LD_LIBRARY_PATH=/home/jkalliau/prgm/wxsvg-1.5.22/src/.libs/ vdiff
```

Or you should copy the library a common search path.

So this a typical linking problem, not a vdiff bug.
