### ISSUE TITLE
vdiff renders chrome with offset

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg-test-suite#16]
#### What happened?
![Screenshot from 2020-03-02 22-15-42](https://user-images.githubusercontent.com/15687581/75718608-8a844300-5cd3-11ea-9858-21a3fa568a3a.png)

#### What should have happened?
|lib|pic|
|-|-|
|svg|![](https://upload.wikimedia.org/wikipedia/commons/9/9d/Diagram_Damage_to_Cancer_Wiki_300dpi.svg)
|ink|![Diagram Damage to Cancer Wiki 300dpi](https://user-images.githubusercontent.com/15687581/75718560-793b3680-5cd3-11ea-8246-256f5803dbc0.png)
|resvg|![Diagram Damage to Cancer Wiki 300dpi_resvg](https://user-images.githubusercontent.com/15687581/75718567-7dffea80-5cd3-11ea-9cc4-161a8eab75d2.png)
|rsvg|![Diagram Damage to Cancer Wiki 300dpi_rsvg](https://user-images.githubusercontent.com/15687581/75718579-80fadb00-5cd3-11ea-88ae-ac42fb6a099f.png)
|chrome|![Screenshot from 2020-03-02 22-15-00](https://user-images.githubusercontent.com/15687581/75718597-86f0bc00-5cd3-11ea-9d77-397f45203184.png)

#### Copyright

source https://commons.wikimedia.org/wiki/File:Diagram_Damage_to_Cancer_Wiki_300dpi.svg

author Bernstein0275

license https://creativecommons.org/licenses/by-sa/3.0/deed.de

#### Version and Operating System:

- Inkscape Version: 1.1dev
- resvg version: 0.9.0
- rsvg Version: 2.40.21
- Operating System: Ubuntu 18.04

**Comment by RazrFalcon** [comment]
You mean the offset?

**Comment by JoKalliauer** [comment]
yes I mean the offset
