### ISSUE TITLE
support Inkscape1

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg-test-suite#17]
Inkscape1 ([not officially released](https://inkscape.org/de/release/inkscape-1.0beta2/)) has a slightly different command line than 0.92.4

Instead of
>inkscape filename.svg --export-png=filename.png

Inkscape1 uses
> inkscape filename.svg  --export-type="png" -w 250

or
>inkscape --without-gui --actions="PNGFilename.png; export-do" filename.svg

more infos can be found at https://wiki.inkscape.org/wiki/index.php/Using_the_Command_Line

If you do not want to implement it: Maybe I can edit the souce-code and recompile?

**Comment by RazrFalcon** [comment]
For now, you can edit this line: https://github.com/RazrFalcon/resvg-test-suite/blob/f23fdaaddc9aeae79db2a2e5d2485b1fe52625f9/tools/vdiff/src/render.cpp#L195

**Comment by JoKalliauer** [comment]
I tried it with 
```bash
    const auto outImg = Paths::workDir() + "/inkscape.png";

    /*const QString out = */Process::run(data.convPath, {
        data.imgPath,
        "-w", QString::number(data.viewSize),
        "--without-gui --actions=\"" + outImg + "; export-do\""
    });
```

But it did not work out, anyhow I found Inkscape 0.92.4 in `/snap/bin/inkscape`, so solved

**Comment by JoKalliauer** [comment]
Is Inkscape 1.0 already supported? It was released in [May 2020](https://inkscape.org/news/2020/05/04/introducing-inkscape-10/).

**Comment by RazrFalcon** [comment]
Yes, I'm testing against it.
