### ISSUE TITLE
./SvgConsole

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg-test-suite#19]
Your Readme linking to https://github.com/vvvv/SVG/issues/614 is a bit unclear.

I installed https://github.com/wieslawsoltes/SVG/tree/SampleConsoleApplication/Samples/SvgConsole

I tried 
```bash
cd /home/jkalliau/Documents/GitHub/resvg-test-suite/tools/svgnetrender
./SvgConsole -f filename.svg
```

and it worked, but saidly it does not work in vdiff
![Screenshot from 2020-03-03 19-58-46](https://user-images.githubusercontent.com/15687581/75809671-6f740a80-5d89-11ea-945e-cb8430d16c65.png)

**Comment by RazrFalcon** [comment]
I never tried using it on Linux. It's a Windows library anyway. I guess you have to add it to `LD_LIBRARY_PATH` too.

**Comment by JoKalliauer** [comment]
I can run added export LD_LIBRARY_PATH=/home/jkalliau/Documents/GitHub/resvg-test-suite/tools/svgnetrender:$LD_LIBRARY_PATH to my libary-path in my .bashrc and I run
```bash
cd /home/jkalliau/Documents/GitHub/resvg-test-suite/tools/vdiff
../svgnetrender/SvgConsole -f /home/jkalliau/Documents/GitHub/cleanupSVG/filename.svg
export LD_LIBRARY_PATH=/home/jkalliau/Documents/GitHub/resvg-test-suite/tools/svgnetrender:$LD_LIBRARY_PATH
vdiff
```
![Screenshot from 2020-03-05 17-52-26](https://user-images.githubusercontent.com/15687581/76004768-547cd400-5f0a-11ea-87e6-57745c7e8be5.png)

This are my vdiff-settings
![Screenshot from 2020-03-05 17-56-11](https://user-images.githubusercontent.com/15687581/76004967-aaea1280-5f0a-11ea-981a-089e5bba137e.png)

Since `../svgnetrender/SvgConsole -f /home/jkalliau/Documents/GitHub/cleanupSVG/filename.svg` works, I expect vdiff does not find `/home/jkalliau/Documents/GitHub/resvg-test-suite/tools/svgnetrender/SvgConsole`. (maybe wrong casesensitive setting)

When I search for `exePath`
```bash
cd ~/Documents/GitHub/resvg-test-suite/tools/vdiff/src
grep -nri 'exePath' .
```
I find 
```bash
./render.cpp:233:    const auto exePath = QString(SRCDIR) + "../wxsvgrender/release/wxsvgrender";
./render.cpp:235:    const auto exePath = QString(SRCDIR) + "../wxsvgrender/wxsvgrender";
./render.cpp:245:    const QString out = Process::run(exePath, {
./render.cpp:262:    const auto exePath = QString(SRCDIR) + "../qtsvgrender/release/qtsvgrender";
./render.cpp:264:    const auto exePath = QString(SRCDIR) + "../qtsvgrender/qtsvgrender";
./render.cpp:268:    const QString out = Process::run(exePath, {
```
But I do not find anything in `resvg-test-suite/tools/vdiff/src` related to 
`svgnetrender/SvgConsole`

can you tell me where the path-data can be found?

**Comment by RazrFalcon** [comment]
That's a bug. Will fix it soon.

**Comment by RazrFalcon** [comment]
SVG.NET is Windows-only, so there is no point in fixing it for other OSes.
