### ISSUE TITLE
[request] add update-button

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg-test-suite#20]
I would like to make a minimal working example (for reducing work of the developers), therfore I would like to rerender the current file. (Everytime I overwrite the file, or add an upload-bottom.)

**Comment by RazrFalcon** [comment]
Ctrl+R?

**Comment by RazrFalcon** [comment]
Nope. You have to restart the app. Will add it later.

**Comment by JoKalliauer** [comment]
No need to restart

changing directory is enough (actually changing is not even necessary), just click save

![Screenshot from 2020-03-06 17-27-10](https://user-images.githubusercontent.com/15687581/76102089-c3703080-5fcf-11ea-94e6-268c00b884ba.png)
