### ISSUE TITLE
Test against Firefox

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg-test-suite#21]
I try to use Firefox, but it does not work out.

I closed all Firefox-sessions.

I use `/usr/lib/firefox/firefox` for firefox, see
![Screenshot from 2020-03-09 16-34-01](https://user-images.githubusercontent.com/15687581/76230513-1e9a6100-6224-11ea-8364-c8642141af1e.png)

I can open firefox using `/usr/lib/firefox/firefox`.

I get the information "Invalid Image: /home/jkalliau/Documents/GitHub/resvg-test-suite/tools/vdiff/firefox.png"
![Screenshot from 2020-03-09 16-42-15](https://user-images.githubusercontent.com/15687581/76231057-f3fcd800-6224-11ea-8353-a60f867b90af.png)

But this file `/home/jkalliau/Documents/GitHub/resvg-test-suite/tools/vdiff/firefox.png` does not exist, but however if I copy "screnshot.png" to "firefox.png"  and refresh with `ctrl` & `r` it shows this image.
![Screenshot from 2020-03-09 16-44-12](https://user-images.githubusercontent.com/15687581/76231238-3aeacd80-6225-11ea-83cd-38240a7cf843.png)

But if I refresh again with `ctrl` & `r` I do not see any image again.

Might it be that the image get rendered at a different place?

**Comment by RazrFalcon** [comment]
You should use Firefox < 61. Later version have a broken screenshot feature.

**Comment by JoKalliauer** [comment]
I extracted https://ftp.mozilla.org/pub/firefox/releases/60.9.0esr/linux-x86_64/de/ in `/home/jkalliau/prgm/firefox` and it works. ;-)

Can I tell this firefox-version somehow to not update if I open it?

My default-browser is firefox (I know some prefer chrome) and I got some rendering-problems when my default browser `/usr/bin/firefox/firefox` is open, can I tell FF60 to be a portable version with local user-settings?

**Comment by RazrFalcon** [comment]
No idea.

**Comment by JoKalliauer** [comment]
I could tell firefox to not update via https://stackoverflow.com/a/44097096/6747994 but that would also affect my current firefox-browser.

However on Linux there is a possibility to run it portable, see https://wiki.ubuntuusers.de/Portable_Firefox/

But this needs to send firefox two options `-no-remote -profile "$PWD/profilordner"`, otherwise it will not render anything as long as I have another firefox-window open.

In vdif-terminal I get 
```bash
firefox: *** You are running in headless mode.
Firefox wird bereits ausgef�hrt, reagiert aber nicht. Um ein neues Fenster �ffnen zu k�nnen, m�ssen Sie zuerst den bestehenden Firefox-Prozess beenden oder Ihren Computer neu starten.
```
If I have another firefox-window open.

Anyway: @RazrFalcon  can you tell me where to add `-no-remote -profile "$PWD/profilordner"´ to firefox I assume https://github.com/RazrFalcon/resvg-test-suite/blob/master/tools/vdiff/src/render.cpp#L93 - L100

**Comment by RazrFalcon** [comment]
I guess it should look like this:

```c
QString out = Process::run(data.convPath, {
    "--no-remote", 
    "--profile", "/home/jkalliau/prgm/firefox-portable/profilordner",
    "--headless",
    "--window-size",
    QString("%1,%2").arg(w).arg(h),
    "--screenshot",
    QFileInfo(outImg).absoluteFilePath(),
    data.imgPath,
}, true);
```

**Comment by JoKalliauer** [comment]
@RazrFalcon  Thanks works perfectly (also if I have another firefox open)
