### ISSUE TITLE
Batik on UNIX: invalid file (bad magic number): Exec format error

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg-test-suite#22]
If I run vdiff
with this settings:
![Bildschirmfoto von 2021-03-18 23-14-36](https://user-images.githubusercontent.com/15687581/111704727-ea4a7f00-883f-11eb-9a19-fb88f84a9aa9.png)

I get
![Bildschirmfoto von 2021-03-18 23-13-14](https://user-images.githubusercontent.com/15687581/111704774-f6ced780-883f-11eb-9386-6643a126b7e7.png)

```bash
Process 'home/jokalliau/prgm/batik-1.14/batik-rasterizer-1.14.jar' finished with an invalid exit code: 1 invalid file (bad magic number: Exec format error
```

It might be related with this issue: https://stackoverflow.com/a/29139336/6747994 or https://stackoverflow.com/a/42646713/6747994

## How I installed batik
```
cd home/jokalliau/prgm
wget https://mirror.klaus-uwe.me/apache//xmlgraphics/batik/binaries/batik-bin-1.14.zip
unzip batik-bin-1.14.zip
```
## Rending with batik
`java -jar ~/prgm/batik-1.14/batik-rasterizer-1.14.jar "$file" -d "${file%.svg}_batik.png"` works

Do I have to choose the *.jar-file or an executable-file?

## Version
OS: Fedora 33
Batik:  1.14

**Comment by RazrFalcon** [comment]
I'm running this bash script:

```
#!/bin/bash

cd /home/razr/Downloads/batik-bin-1.13/
java -jar batik-rasterizer-1.13.jar "${@}"
```

**Comment by JoKalliauer** [comment]
There was a cache-problem:

I had to delete `~/Dokumente/GitDesktop/resvg-test-suite/tools/vdiff/images` . now batik and inkscape works.

Maybe "ctrl" & "r" or the sync-Button should also clear the cache and the current image in `resvg-test-suite/tools/vdiff/images`?

**Comment by RazrFalcon** [comment]
No one except me should use vdiff anyway.
