### ISSUE TITLE
W3C test suite Revision version differs between png and svg

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg-test-suite#23]
The PNG has "$Revision 1.5$", but the SVG has "DRAFT" at the top

![W3C](https://user-images.githubusercontent.com/15687581/111899538-81285e80-8a2d-11eb-8cf0-b966a392e2a5.png)

![Bildschirmfoto von 2021-03-21 10-09-31](https://user-images.githubusercontent.com/15687581/111899554-9f8e5a00-8a2d-11eb-8895-fd8624aa236b.png)

**Comment by RazrFalcon** [comment]
Yes, because the official tests suite is garbage.

**Comment by JoKalliauer** [comment]
Sorry, that's the issue of the [test suite](https://www.w3.org/Graphics/SVG/Test/20110816/archives/W3C_SVG_11_TestSuite.tar.gz)
