### ISSUE TITLE
update official.csv for librsvg 2.5X

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg-test-suite#24]
I use librsvg 2.50.3 and the following librsvg-results might be outdated (maybe I have overseen something)

* render-groups-03-t.svg (crash=>fail)
* styling-css-02-b.svg (fail => passed)
* styling-css-08-f.svg (fail => passed)
* styling-pres-04-f.svg (fail => passed)
* filters-overview-01-b  (fail => passed?)
* filters-overview-02-b   (fail => passed?)
* filters-overview-03-b  (fail => passed?)
* styling-css-04-f_vdiff

I know it is difficult to keep them up-to-date, so I understand if you do not want to update to each version.

![W3C_SVG_11_TestSuite_render-groups-03-t svg](https://user-images.githubusercontent.com/15687581/111904243-3404b680-8a46-11eb-900d-6a2edbb64f16.png)

![W3C_SVG_11_TestSuite_styling-css-02-b svg](https://user-images.githubusercontent.com/15687581/111904249-3ebf4b80-8a46-11eb-96a5-79e56a9b0edb.png)

![W3C_SVG_11_TestSuite_styling-css-08-f svg](https://user-images.githubusercontent.com/15687581/111904259-454dc300-8a46-11eb-9e2a-e24d785e59e3.png)

![W3C_SVG_11_TestSuite_styling-pres-04-f svg](https://user-images.githubusercontent.com/15687581/111904260-4a127700-8a46-11eb-94ec-b0b740bb6b03.png)

![filters-overview-01-b_vdiff](https://user-images.githubusercontent.com/15687581/113516794-8bde0a00-957c-11eb-95c6-a9fe17dffca0.png)

![filters-overview-02-b_vdiff](https://user-images.githubusercontent.com/15687581/113516814-a44e2480-957c-11eb-8f74-1592e6d70027.png)

![filters-overview-03-b_vdiff](https://user-images.githubusercontent.com/15687581/113516845-d495c300-957c-11eb-9793-557cf02f637c.png)

![styling-css-04-f_vdiff](https://user-images.githubusercontent.com/15687581/113517205-d5c7ef80-957e-11eb-8c39-dcbb3cdd3246.png)

----
edit:
Update to resvg 0.14

* conform-viewers-02-f (fail=>pass)
* text-tref-02-b (fail => crash) returing an error without rendering is imho like crashing
* filters-composite-04-f (fail =>pass?)
* struct-image-10-t (fail => pass?)
* struct-image-13-f  (fail => pass?)
* struct-image-14-f 
* struct-image-15-f 

![](https://upload.wikimedia.org/wikipedia/commons/1/19/W3C_SVG_11_TestSuite_conform-viewers-02-f_vdiff.png)
![](https://upload.wikimedia.org/wikipedia/commons/3/31/W3C_SVG_11_TestSuite_struct-frag-04-t_vdiff.png)
![filters-composite-04-f_vdiff](https://user-images.githubusercontent.com/15687581/113516692-f6427a80-957b-11eb-8bf3-da67a9488145.png)
![struct-image-10-t_vdiff](https://user-images.githubusercontent.com/15687581/113516932-571e8280-957d-11eb-8c24-560f5c9f10b8.png)
![struct-image-13-f_vdiff](https://user-images.githubusercontent.com/15687581/113517010-baa8b000-957d-11eb-9af5-97ddc2654588.png)

----
update chrome:

* filters-light-01-f_vdiff  (fail => passed?)
* struct-image-13-f  (fail => pass?)
* struct-image-14-f 
* struct-image-15-f 

![filters-light-01-f_vdiff](https://user-images.githubusercontent.com/15687581/113516747-4ae5f580-957c-11eb-963a-f4be8f0ff3a8.png)
![struct-image-13-f_vdiff](https://user-images.githubusercontent.com/15687581/113517010-baa8b000-957d-11eb-9af5-97ddc2654588.png)
----
edit batik

* struct-image-09-t (crash => pass?)
* struct-image-13-f  (crash => fail)
* struct-image-14-f 
* struct-image-15-f 
* text-fonts-203-t (fail => pass)

![struct-image-09-t_vdiff](https://user-images.githubusercontent.com/15687581/113516902-30f8e280-957d-11eb-9b52-c73cde9fcfd2.png)
![grafik](https://user-images.githubusercontent.com/15687581/113517023-d1e79d80-957d-11eb-9455-74299eb4a0f8.png)
![text-fonts-203-t_vdiff](https://user-images.githubusercontent.com/15687581/113517253-0e67c900-957f-11eb-8b92-295d516a086e.png)

----
update Inkscape

* struct-image-13-f  (fail => passed)
* struct-image-14-f 
* struct-image-15-f 
* text-fonts-204-t

![grafik](https://user-images.githubusercontent.com/15687581/113517023-d1e79d80-957d-11eb-9455-74299eb4a0f8.png)
![text-fonts-204-t_vdiff](https://user-images.githubusercontent.com/15687581/113517284-3bb47700-957f-11eb-81a1-d7d2cbe7b836.png)

----
update wxSVG

* struct-image-13-f  (fail => passed)
* struct-image-14-f 
* struct-image-15-f 
* struct-use-07-b_vdiff

![grafik](https://user-images.githubusercontent.com/15687581/113517023-d1e79d80-957d-11eb-9455-74299eb4a0f8.png)
![struct-use-07-b_vdiff](https://user-images.githubusercontent.com/15687581/113517191-bd57d500-957e-11eb-8c31-7b7047e1e3ab.png)

**Comment by RazrFalcon** [comment]
Those tests are not used anywhere anymore. Only resvg tests itself are (root `svg` and `png` dirs).
Thanks anyway, I will update it.
