### ISSUE TITLE
e-radialGradient-031: Focal point correction changed in SVG2

### ISSUE THREAD

**Issue by jwmcglynn** [RazrFalcon/resvg-test-suite#43]
This test is validating focal point correction, but that was changed in SVG2, from https://www.w3.org/TR/SVG2/pservers.html#RadialGradientNotes:

> f the start circle defined by ‘fx’, ‘fy’ and ‘fr’ lies outside the end circle defined by ‘cx’, ‘cy’, and ‘r’, effectively a cone is created, touched by the two circles. Areas outside the cone stay untouched by the gradient (transparent black).

So instead of correcting the focal point, it now draws a cone.  Based on that, I believe the test should render as follows:

![With cone](https://user-images.githubusercontent.com/103489/155903792-b84ea5eb-fbbe-43e3-bdf0-117f6457ebf5.png)

However, the golden in the test suite renders as follows: 
![actual e-radialGradient-031](https://github.com/RazrFalcon/resvg-test-suite/blob/master/png/e-radialGradient-031.png?raw=true)

Chrome appears to render in the same way with a cone, so I think that the results of the test suite are backwards.

The spec appears to be worded without mentioning backwards compatibility, should the SVG2 behavior be used for all files?

**Comment by RazrFalcon** [comment]
Hm... It seems that you are right. I still have no idea how to handle SVG 1 and 2 differences/breaking changes. For now, we do target SVG 2. So the test should be updated.

Here is how it currently looks like:

![e-radialGradient-031](https://user-images.githubusercontent.com/725494/157070244-1595880b-ab4e-4964-bb8e-fa3549370ae8.png)
