### ISSUE TITLE
[vdiff] inkscape does not work on Gnome, but on KDE and Xfce

### ISSUE THREAD

**Issue by JoKalliauer** [RazrFalcon/resvg-test-suite#44]
I don't know why `inkscape.x86_64 1.2.2-7.fc38` works on [KDE](https://en.wikipedia.org/wiki/KDE_Plasma_5) and [Xfce](https://en.wikipedia.org/wiki/Xfce), but not on [Gnome](https://en.wikipedia.org/wiki/GNOME)

|Gnome|Gnome on Xorg|Plasma (Wayland)|Plasma(X11)|Xfce|
|---|---|---|---|---|
|![Screenshot from 2023-05-21 00-59-05_GNOME](https://github.com/RazrFalcon/resvg-test-suite/assets/15687581/5e7ca963-b5df-4b94-a62b-123edfac4757)|![Screenshot from 2023-05-21 00-57-46_GNOME on Xorg](https://github.com/RazrFalcon/resvg-test-suite/assets/15687581/af27f42f-8e78-4f9f-86dd-3baac6d6df32)|![Screenshot_20230521_005534](https://github.com/RazrFalcon/resvg-test-suite/assets/15687581/4c0ee082-941f-41e3-9862-9464e4ecbd6e)|![Screenshot_20230521_005332_Plasma (X11)](https://github.com/RazrFalcon/resvg-test-suite/assets/15687581/9e4f4dde-91ec-4d2f-a345-eee609788b0b)|![Screenshot_2023-05-21_00-52-16_Xfce Session](https://github.com/RazrFalcon/resvg-test-suite/assets/15687581/3492192e-cd5e-4440-871a-a8a1ae4666c4)|

```
hostnamectl
     Static hostname: lws84.imws.tuwien.ac.at
           Icon name: computer-laptop
             Chassis: laptop 💻
          Machine ID: 96434f58f7644401a3f9d69da903899d
             Boot ID: 1113ece2f1854fcb992bc27461a9d177
    Operating System: Fedora Linux 38 (Workstation Edition)
         CPE OS Name: cpe:/o:fedoraproject:fedora:38
      OS Support End: Tue 2024-05-14
OS Support Remaining: 11month 2w 6d
              Kernel: Linux 6.2.15-300.fc38.x86_64
        Architecture: x86-64
     Hardware Vendor: Lenovo
      Hardware Model: ThinkPad P15 Gen 1
    Firmware Version: N30ET49W (1.32 )
       Firmware Date: Wed 2022-12-14
```

```
lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 38 (Thirty Eight)
Release:	38
Codename:	ThirtyEight
```

**Comment by JoKalliauer** [comment]
reported upstream: https://gitlab.com/inkscape/inbox/-/issues/8656

Inkscape in Gnome creates the out.png , but ends with `Segmentation fault (core dumped)`.

If inkscape creates the image, but terminates with a Segmenation fault, does vdiff still display the output?

**Comment by RazrFalcon** [comment]
It should draw the error message.

**Comment by JoKalliauer** [comment]
vdiff returns 
```
Process /usr/bin/inkscape'
finished with an invalid error code:
11
```

It seems to be the expected behaviour.

**Comment by JoKalliauer** [comment]
vdiff returns 
```
Process /usr/bin/inkscape'
finished with an invalid error code:
11
```

It seems to be the expected behaviour.
