### ISSUE TITLE
Issue with `structure/transform/rotate-at-position.svg`?

### ISSUE THREAD

**Issue by LaurenzV** [RazrFalcon/resvg-test-suite#45]
The svg is as follows:
```svg
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <title>`rotate-at-position`</title>

    <!-- should be covered -->
    <path id="path1" d="M 99,14.14 L 183.8,99 L 99,183.85 L 14.14,99 Z" fill="red"/>

    <g id="g1" transform="rotate(45, 100, 50)">
        <rect id="rect1" x="75" y="25" width="120" height="120" fill="green"/>
    </g>

    <!-- image frame -->
    <rect id="frame" x="1" y="1" width="198" height="198" fill="none" stroke="black"/>
</svg>
```

It says that the red path should be covered, but even in the resvg reference pictures it is not completely covered:
![rotate-at-position](https://github.com/RazrFalcon/resvg-test-suite/assets/47084093/7913e027-e02f-4b6e-8c6f-b8625eed7599)

Same applies to when opening the svg directly in Chrome/Firefox.

Is there something wrong with the description or am I missing something else?

**Comment by RazrFalcon** [comment]
This is just a round error. You can ignore it. Will update the test to make it clearer.
