### ISSUE TITLE
Tests `marker-on-rounded-rect` and `orient=audo-on-M-C-C-4` wrong

### ISSUE THREAD

**Issue by LaurenzV** [RazrFalcon/resvg-test-suite#46]
I think the two tests in this repository are outdated/wrong.

In the case of `orient=auto-on-M-C-C-4`, the marker at the top is in the wrong direction I think.
[The reference file for this repository](https://github.com/RazrFalcon/resvg-test-suite/blob/master/tests/painting/marker/orient%3Dauto-on-M-C-C-4.png)
[The reference file in the resvg repository](https://github.com/RazrFalcon/resvg/blob/master/crates/resvg/tests/tests/painting/marker/orient%3Dauto-on-M-C-C-4.png)

In the case of `marker-on-rounded-rect`, the markers are completely missing.
[The reference file for this repository](https://github.com/RazrFalcon/resvg-test-suite/blob/master/tests/painting/marker/marker-on-rounded-rect.png)
[The reference file in the resvg repository](https://github.com/RazrFalcon/resvg/blob/master/crates/resvg/tests/tests/painting/marker/marker-on-rounded-rect.png)

**Comment by RazrFalcon** [comment]
Thanks. Will update.

**Comment by RazrFalcon** [comment]
In case of `orient=auto-on-M-C-C-4`, the top arrow can point left or right. Both outputs are "correct".
