### ISSUE TITLE
Upgrade Chrome to the latest stable version

### ISSUE THREAD

**Issue by yisibl** [RazrFalcon/resvg-test-suite#49]
The current stable version is 120.

Chrome 119 has [upgraded clip-path](https://chromestatus.com/feature/5068167415595008). The following cases are now supported:

- `Circle shorthand with `stroke-box` (SVG 2)`
- `Circle shorthand with `view-box` (SVG 2)`

https://razrfalcon.github.io/resvg-test-suite/svg-support-table.html#_masking

**Comment by RazrFalcon** [comment]
Yes, I know. Re-running tests is a long a complicated process. It will be done when it will be done.
