### ISSUE TITLE
How are PNGs of test files generated?

### ISSUE THREAD

**Issue by Michael5601** [RazrFalcon/resvg-test-suite#51]
I appreciate your effort on this test suite and I use it right now to evaluate the results of the java libraries JSVG, svgSalamander, Batik and EchoSVG. 

One thing I don't quite understand is where the PNG references come from? Did you get them from somewhere or did you use a renderer that would potentially create wrong references?

Kind regards
Michael

**Comment by RazrFalcon** [comment]
Most of the reference PNGs are generated via `resvg` and Chrome and represent an expected output.

Could a reference be "wrong"? That's unlikely, but possible. After all, SVG doesn't have a reference implementation and no one knows how a "correct" output suppose to look like.

**Comment by Michael5601** [comment]
Thank you for this info.

So in the chart of the test results you provided, the tests that resvg failed are only tests where resvg crashed or where chrome was the reference?

**Comment by RazrFalcon** [comment]
Yep, you're correct.

Is this a `mix-blend-mode` test? Most SVG libraries do not support it. It's a relatively new addition. So what you see is not surprising. The reference image is correct.

**Comment by Michael5601** [comment]
This is the test `painting/isolation - As property (SVG2)` and it uses `mix-blend-mode` so your are right with the reference.

```
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <title>As property (SVG 2)</title>
    <desc>`isolation` must be set only inside `style` element or attribute.</desc>

    <linearGradient id="lg1">
        <stop offset="0" stop-color="white" stop-opacity="0"/>
        <stop offset="1" stop-color="yellow"/>
    </linearGradient>

    <rect id="rect1" x="20" y="20" width="140" height="140" fill="green"/>
    <g id="g1" isolation="isolate">
        <rect id="rect2" x="40" y="40" width="140" height="140" fill="url(#lg1)"
              style="mix-blend-mode:overlay"/>
    </g>


    <!-- image frame -->
    <rect id="frame" x="1" y="1" width="198" height="198" fill="none" stroke="black"/>
</svg>
```

**Comment by RazrFalcon** [comment]
Yes, `isolation` and `mix-blend-mode` depend on each other. And yes, the reference image is correct.
Basically, most SVG libraries do not support SVG 2 features and this is one of them.
